export { default as ConfirmDialog } from "./ConfirmDialog.vue";
export { default as EnterTextDialog } from "./EnterTextDialog.vue";
export { default as EditTagsDialog } from "./EditTagsDialog.vue";
export { default as ElementVersionManagementDialog } from "./ElementVersionManagementDialog.vue";
export { default as HelpDialog } from "./HelpDialog.vue";
export { default as PasswordChangeDialog } from "./PasswordChangeDialog.vue";
export { default as PermissionDialog } from "./PermissionDialog.vue";
export { default as SelectNewVersionDialog } from "./SelectNewVersionDialog.vue";
export { default as UserDialog } from "./UserDialog.vue";
